import { Experience } from "@/lib/types";

export const EXPERIENCE: Experience[] = [
  {
    company: "Stealth AI Startup",
    role: "Founding Engineer",
    startTime: "2024-06",
    endTime: "2024-09",
    location: "New York, USA - Remote",
    logo: "/experiences/stealth.jpeg",
    link: "#",
    bullets: [
      "Worked directly with the founder (ex-Chief Product Designer at Ramp)",
      "Cut infra costs from 300$/month to almost zero by migrating from AWS/Terraform to Cloudflare Workers & Supabase",
      "Refactored a tangled Next.js monolith into a clean Turborepo monorepo with separated packages and apps",
      "Shipped a Chrome extension (Plasmo) and built internal developer tooling - a CLI for monorepo management (env handling, CF bindings generation, package scaffolding with template configs)",
      "Optimized the web app, cut the load times in almost 1/2 and add caching + used tanstack prefetch architecture + nextjs slots to make it feel much more snappy and responsive",
      "Built the design system into a fully reusable component library with Storybook",
    ],
    techStack: [
      "TypeScript",
      "Next.js",
      "Turborepo",
      "Storybook",
      "Plasmo",
      "Workers",
      "Prisma",
      "Hono",
    ],
  },
  {
    company: "SDSLabs",
    role: "Developer",
    logo: "/experiences/sdslabs.svg",
    startTime: "2023-04",
    location: "IIT Roorkee",
    link: "https://team.sdslabs.co/",
    bullets: [
      "Student-run tech organization at IIT Roorkee. Built and maintained internal tools used by 1000+ students every year, and contributed to various open source projects.",
      "[Quizio](https://quizio.sdslabs.co/) - Live quizzing platform supporting 2,000+ concurrent users. Built the onboarding flow and optimized the live quiz pipeline, then stepped up as mentor leading full development with patches and performance improvements.",
      "Zeus - OCI-compatible container runtime in Go, built from scratch. Architecting and mentoring the project development.",
      "Accounts (RBAC) - Designed and built a complete RBAC system for SDSLabs' own auth platform (sign in with SDSLabs), built on Ory Kratos + Keto.",
      "[Dex](https://dex.sdslabs.co/) - Created and leading its development. AI-powered knowledge base used across tech clubs for shared resources, creating slack bots, and idea exploration from their resources via Claude/ChatGpt MCP integration. 100+ beta users, Chrome extension and public launch incoming.",
    ],
    techStack: [
      "Go",
      "React",
      "TypeScript",
      "Python",
      "CI/CD",
      "AWS",
      "Docker",
      "Postgres",
      "Ory",
    ],
  },
  {
    company: "Uniswap Hook Incubator",
    role: "Cohort Fellow",
    startTime: "2025-10",
    endTime: "2025-12",
    logo: "/experiences/uhi.png",
    location: "Remote",
    link: "https://explorer.zora.energy/token/0x11158a1751eA90124715F5bE2474BD05d284858b/instance/48",
    bullets: [
      "Selected as one of the top 100 fellows worldwide for the Uniswap Hook Incubator program",
      "Built a dutch auction hook on Uniswap V4, allowing users to create and participate in gas-efficient auctions directly on the Uniswap interface.",
    ],
    techStack: ["Solidity", "Uniswap V4", "Foundry"],
  },
  {
    company: "WatchOut!",
    role: "Editor",
    startTime: "2023-03",
    endTime: "2024-02",
    logo: "/experiences/watchout.jpeg",
    location: "IIT Roorkee",
    link: "https://watchout.iitr.ac.in/",
    bullets: [
      "Student-run media organization at IIT Roorkee",
      "Covered events, wrote articles and was part of the design team for magazine",
    ],
    techStack: ["Writing", "Photography", "Design"],
  },
];
